version: '3'
services:
    nginx:
        image: nginx:latest
        ports:
            - '8080:80'
        volumes:
            - './docker/default.conf:/etc/nginx/conf.d/default.conf'
            - './:/usr/share/nginx/html'